const labels: Record<string, string> = {
  "Corroborated": "Bukti selaras",
  "Mixed Evidence": "Bukti bercampur",
  "Insufficient Evidence": "Bukti belum cukup",
  "Supported": "Mendukung",
  "Adverse": "Berlawanan",
  "Mixed": "Bercampur",
  "Unrelated": "Tidak terkait",
  "Unverified": "Belum terverifikasi",
  "Source Conflict": "Konflik sumber",
  "Concentrated Flow": "Arus terkonsentrasi",
  "Broad Participation": "Partisipasi luas",
  "Foreign Alignment": "Arus asing selaras",
  "Normal": "Normal",
  "Elevated": "Meningkat",
  "Extreme": "Ekstrem",
  "Insufficient Data": "Data belum cukup",
  "Market-aligned": "Mengikuti pasar",
  "Sector-led": "Dipengaruhi sektor",
  "Idiosyncratic": "Khusus emiten",
  "Primary test": "Uji utama",
  "Supporting": "Pendukung",
  "Open": "Belum diuji",
  "High": "Tinggi",
  "Medium": "Sedang",
  "Low": "Rendah",
  "New": "Baru",
  "Updated": "Diperbarui",
  "leading": "Utama",
  "plausible": "Mungkin",
  "challenged": "Lemah",
  "Observed correlation": "Korelasi teramati",
  "Reported input": "Masukan terlapor",
  "Causal hypothesis": "Hipotesis sebab akibat",
  "Company exposure": "Eksposur emiten",
  "Financial observable": "Indikator keuangan",
  "Aggregation point": "Titik penghubung",
  // Metric tiles: the engine keeps the technical name (retrieval and the
  // figure matcher key on it); the reader sees what the number measures.
  "HHI": "HHI konsentrasi (0–1)",
  "Peserta efektif": "Jumlah broker efektif",
  "Skor z tahan pencilan": "Skor z volume (0 = biasa)",
  "Residual setelah beta": "Gerak di luar IHSG",
  "source": "Sumber",
  "mechanism": "Mekanisme",
  "company": "Emiten",
  "observation": "Indikator",
  "business-impact": "Dampak bisnis",
  "concentration": "Konsentrasi",
  "momentum": "Momentum",
  "catalyst": "Katalis",
  "weather": "Cuaca",
  "macro": "Makro",
  "commodity": "Komoditas",
  "filing": "Keterbukaan",
  "sectors": "Sectors",
  "policy": "Kebijakan",
  "market": "Pasar",
  "financial": "Keuangan",
  "volume": "Volume operasi",
  "pricing": "Realisasi harga",
  "margin": "Margin operasi",
  "cash-flow": "Arus kas operasi",
  "balance-sheet": "Kapasitas neraca",
  "valuation": "Dampak valuasi",
  "Basic Materials": "Bahan dasar",
  "Energy": "Energi",
  "Technology": "Teknologi",
  "Financials": "Keuangan",
  "Infrastructure": "Infrastruktur",
  "Diversified Metals & Minerals": "Logam dan mineral",
  "Diversified Metals": "Logam terdiversifikasi",
  "Nickel": "Nikel",
  "Tin": "Timah",
  "Banks": "Perbankan",
  "Telecommunication": "Telekomunikasi",
  "Toll Roads": "Jalan tol",
  "Digital Platforms": "Platform digital",
  "Digital Commerce": "Perdagangan digital",
  "Media & Technology": "Media dan teknologi",
  "Gas Distribution": "Distribusi gas",
  "Coal": "Batu bara",
  "Packaged Food": "Makanan kemasan",
  "Food Retail": "Ritel makanan",
  "Consumer": "Konsumen",
  "Market": "Pasar",
  "rates": "Suku bunga",
  "currency": "Mata uang",
  "flows": "Arus dana",
  "sentiment": "Sentimen",
  "Nickel Mining": "Tambang nikel",
  "Tin Mining": "Tambang timah",
  "Coal Production": "Produksi batu bara",
  "Oil & Gas Storage & Distribution": "Penyimpanan dan distribusi gas",
};

/** Both sides of the label table, for the check that an English answer did
 *  not keep an Indonesian label (`lib/agent/llm/language-leak.ts`). */
export function labelVocabulary(): { indonesian: string[]; english: string[] } {
  return { indonesian: Object.values(labels), english: Object.keys(labels) };
}

export function uiLabel(value: string | undefined) {
  if (!value) return "";
  return labels[value] ?? value;
}

export function dispositionLabel(kind: "escalate" | "monitor" | "dismiss") {
  if (kind === "escalate") return "Lanjutkan riset";
  if (kind === "monitor") return "Pantau indikator";
  return "Abaikan pemicu";
}
